---
# This file is managed via modulesync
# https://github.com/voxpupuli/modulesync
# https://github.com/voxpupuli/modulesync_config
HOSTS:
  archlinux-2-x64:
    platform: archlinux-2-x86_64
    hypervisor: docker
    image: pierres/archlinux
    docker_preserve_image: true
    docker_cmd: '["/usr/lib/systemd/systemd"]'
    docker_image_commands:
      - 'systemctl mask getty@tty1.service'
CONFIG:
  trace_limit: 200
  masterless: true
...
# vim: syntax=yaml
